# -*- coding: utf-8 -*-
"""Copy_of_Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Ifthii123/Processed_student_Scores_-CSV-Files/blob/main/Copy_of_Untitled7.ipynb
"""

import csv
    data=[
    ["name","math","science","english",],
    ["Alex",80,78,85,],
    ["George",75,60,74,],
    ["Ali", 60,85,90,],
    ["Simon",75,85,80,],
    ["Jack",60,78,90,],
]

# save the raw data
    with open ("raw_student_scores.csv","w",newline="") as file:
    writer=csv.writer(file)
    writer.writerows(data)
    print("Raw CSV files saved successfully")

from google.colab import files
files.download('raw_student_scores.csv')



import csv
def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    elif score >= 50:
        return "E"
    else:
        return "F"

processed_data = [["name", "math", "science", "english", "average", "grade", "math_grade", "science_grade", "english_grade", "min_score", "max_score", "score_range", "pass_fail"]]

for row in data[1:]:
    name, math, science, english = row

    avg_score = (math + science + english) / 3
    overall_grade = get_grade(avg_score)
    math_grade = get_grade(math)
    science_grade = get_grade(science)
    english_grade = get_grade(english)
    min_score = min(math, science, english)
    max_score = max(math, science, english)
    score_range = max_score - min_score
    pass_fail = "Congratulations, you passed!" if avg_score >= 50 else "Fail"

    processed_data.append([name, math, science, english, avg_score, overall_grade, math_grade, science_grade, english_grade, min_score, max_score, score_range, pass_fail])

# Save the processed data
with open("processed_student_scores.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(processed_data)

print("Processed CSV file saved successfully")



with open ("processed_student_scores.csv","w",newline="") as file:
      writer=csv.writer(file)
      writer.writerows(processed_data)
      print ("processed csv file saved successfully")

